env:
    browser: true
    commonjs: true
    es2021: true
extends:
    - google
parserOptions:
    ecmaVersion: 12
rules:
    max-len: 0
    indent: ['error', 4]
    require-jsdoc: 0
    curly: 0
    linebreak-style: ["error", "windows"]
